### ISSUE TITLE
Update slice with mouse scroll

### ISSUE THREAD

**Issue by Irev-Dev** [Irev-Dev/MRI-Volume-Slice#10]
Feature request: Scrolling the mouse when on an image will scroll through slices on that view.

Currently when you click and drag and on one image the other two update (showing a cross-section that matches the mouse coordinates), but it would be good and intuitive to be-able to scroll throw the slices of the images you are currently mousing over by scrolling the mouse.

Should be reasonably easy for someone to have a go at as we already have event listeners setup, just more will need to be added. Have a look at what's happening in `updateCanvases()` and see if that function should be updated or a new function created. The current slice locations are stored in `this.currentView` so this should only need to be incremented/decremented and then existing functions called to update the canvases.

**Comment by elistone** [comment]
I can look into this one.

**Comment by Irev-Dev** [comment]
fixed with PR #13 🥇
