### ISSUE TITLE
Loading state while data is being fetched.

### ISSUE THREAD

**Issue by Irev-Dev** [Irev-Dev/MRI-Volume-Slice#22]
Ever since PR #20 we are fetching data from openneuro.org, this takes a while while (5-15s I'm guessing) It would be good to have something displaying "loading" or similar while this is happening.

**Comment by JonatanSCS** [comment]
Working on this issue, wait for PR! ;)

**Comment by Irev-Dev** [comment]
Fixed in #23, Thanks @JonatanSCS 👏
